import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import {
  ArrowDownRight, ArrowLeft, ArrowUpRight, Bell, Box, CalendarDays, ChevronDown,
  CircleDollarSign, Download, LayoutDashboard, Menu, MoreHorizontal, Package, Plus,
  Search, Settings, ShoppingBag, SlidersHorizontal, Store, Users, WalletCards, X,
} from 'lucide-react'
import { fallbackProducts, fallbackSales } from '../data'
import { Logo, StatusPill, ThemeToggle, peso } from './UI'

const navItems = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard },
  { id: 'sales', label: 'Sales directory', icon: CircleDollarSign },
  { id: 'products', label: 'Products', icon: Package },
  { id: 'customers', label: 'Customers', icon: Users },
]

function Sidebar({ active, setActive, open, setOpen, onStore, onLogout }) {
  return (
    <>
      <AnimatePresence>{open && <motion.button initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setOpen(false)} className="fixed inset-0 z-40 bg-black/40 backdrop-blur-sm lg:hidden" />}</AnimatePresence>
      <aside className={`fixed inset-y-0 left-0 z-50 flex w-[270px] flex-col border-r border-zinc-200 bg-white p-5 transition-transform dark:border-white/10 dark:bg-[#0d0d10] lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex h-12 items-center justify-between px-2"><Logo onClick={() => setActive('overview')} /><button onClick={() => setOpen(false)} className="icon-btn lg:hidden"><X size={18} /></button></div>
        <div className="mt-7 rounded-2xl bg-zinc-100 p-3 dark:bg-white/[.055]"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-zinc-950 text-white dark:bg-acid dark:text-ink"><Store size={17} /></div><div className="min-w-0"><p className="truncate text-sm font-semibold">AUDIA Flagship</p><p className="text-[10px] text-zinc-500">Main storefront</p></div><ChevronDown size={14} className="ml-auto text-zinc-500" /></div></div>
        <nav className="mt-7 space-y-1"><p className="mb-3 px-3 text-[9px] font-bold uppercase tracking-[.18em] text-zinc-400">Workspace</p>{navItems.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setActive(id); setOpen(false) }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition ${active === id ? 'bg-zinc-950 text-white dark:bg-acid dark:text-ink' : 'text-zinc-500 hover:bg-zinc-100 hover:text-zinc-950 dark:hover:bg-white/5 dark:hover:text-white'}`}><Icon size={17} /> {label}{id === 'sales' && <span className={`ml-auto rounded-full px-2 py-0.5 text-[9px] ${active === id ? 'bg-white/15 dark:bg-black/10' : 'bg-zinc-100 dark:bg-white/5'}`}>148</span>}</button>)}</nav>
        <div className="mt-auto space-y-1 border-t border-zinc-200 pt-4 dark:border-white/10"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-zinc-500 hover:bg-zinc-100 dark:hover:bg-white/5"><Settings size={17} /> Settings</button><button onClick={onStore} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-zinc-500 hover:bg-zinc-100 dark:hover:bg-white/5"><ArrowLeft size={17} /> View storefront</button><button onClick={onLogout} className="w-full px-3 pt-3 text-left text-[11px] text-zinc-400 hover:text-rose-500">Sign out of admin</button></div>
      </aside>
    </>
  )
}

function DashboardHeader({ active, theme, setTheme, setOpen }) {
  const current = navItems.find((item) => item.id === active)?.label || 'Dashboard'
  return <header className="sticky top-0 z-30 flex h-[78px] items-center justify-between border-b border-zinc-200 bg-stone-50/90 px-5 backdrop-blur-xl dark:border-white/10 dark:bg-ink/90 sm:px-8"><div className="flex items-center gap-3"><button onClick={() => setOpen(true)} className="icon-btn lg:hidden"><Menu size={19} /></button><div><p className="text-[10px] uppercase tracking-[.15em] text-zinc-400">Administration</p><h1 className="font-display text-xl font-semibold">{current}</h1></div></div><div className="flex items-center gap-2"><button className="icon-btn relative" aria-label="Notifications"><Bell size={18} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-rose-500" /></button><ThemeToggle theme={theme} setTheme={setTheme} compact /><div className="ml-1 hidden items-center gap-3 border-l border-zinc-200 pl-4 dark:border-white/10 sm:flex"><div className="grid h-9 w-9 place-items-center rounded-full bg-violet-100 text-xs font-bold text-violet-700 dark:bg-violet-400/15 dark:text-violet-300">AJ</div><div><p className="text-xs font-semibold">AUDIA Admin</p><p className="text-[10px] text-zinc-500">Store manager</p></div></div></div></header>
}

function StatCard({ icon: Icon, label, value, change, up = true, accent }) {
  return <motion.div whileHover={{ y: -4 }} className="surface-card p-5 sm:p-6"><div className="flex items-start justify-between"><div className={`grid h-11 w-11 place-items-center rounded-2xl ${accent}`}><Icon size={19} /></div><span className={`flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-semibold ${up ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300' : 'bg-rose-100 text-rose-700 dark:bg-rose-400/10 dark:text-rose-300'}`}>{up ? <ArrowUpRight size={12} /> : <ArrowDownRight size={12} />}{change}</span></div><p className="mt-6 text-xs text-zinc-500">{label}</p><p className="mt-2 font-display text-2xl font-semibold tracking-tight">{value}</p></motion.div>
}

function SalesChart() {
  const values = [48, 56, 43, 71, 62, 78, 67, 88, 74, 96, 84, 100]
  return <div className="surface-card p-6"><div className="flex items-start justify-between"><div><h2 className="font-display text-lg font-semibold">Revenue performance</h2><p className="mt-1 text-xs text-zinc-500">September 1–7 compared with last period</p></div><button className="secondary-btn px-3 py-2 text-xs"><CalendarDays size={14} /> This week <ChevronDown size={12} /></button></div><div className="mt-8 flex h-64 items-end gap-2 sm:gap-3">{values.map((value, index) => <div key={index} className="group flex h-full flex-1 items-end"><motion.div initial={{ height: 0 }} animate={{ height: `${value}%` }} transition={{ delay: index * .04, duration: .55 }} className={`relative w-full rounded-t-md ${index === 9 ? 'bg-violet-500 dark:bg-acid' : 'bg-zinc-200 hover:bg-violet-300 dark:bg-white/10 dark:hover:bg-white/20'}`}><span className="absolute -top-7 left-1/2 hidden -translate-x-1/2 rounded bg-zinc-950 px-2 py-1 text-[9px] text-white group-hover:block">{peso(value * 620)}</span></motion.div></div>)}</div><div className="mt-3 flex justify-between text-[9px] uppercase tracking-widest text-zinc-400"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div>
}

function RecentSales({ sales, onViewAll }) {
  return <div className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-zinc-200 p-5 dark:border-white/10"><div><h2 className="font-display text-lg font-semibold">Recent sales</h2><p className="mt-1 text-xs text-zinc-500">Latest completed and active orders</p></div><button onClick={onViewAll} className="text-xs font-semibold hover:underline">View all</button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="text-[9px] uppercase tracking-[.15em] text-zinc-400"><th className="px-5 py-4 font-semibold">Order</th><th className="px-5 py-4 font-semibold">Customer</th><th className="px-5 py-4 font-semibold">Product</th><th className="px-5 py-4 font-semibold">Status</th><th className="px-5 py-4 text-right font-semibold">Total</th></tr></thead><tbody className="divide-y divide-zinc-100 dark:divide-white/5">{sales.slice(0, 5).map((sale) => <tr key={sale.id} className="text-xs transition hover:bg-zinc-50 dark:hover:bg-white/[.025]"><td className="px-5 py-4 font-semibold">{sale.id}</td><td className="px-5 py-4"><p className="font-medium">{sale.customer}</p><p className="mt-1 text-[10px] text-zinc-500">{sale.email}</p></td><td className="max-w-[180px] truncate px-5 py-4 text-zinc-500">{sale.product}</td><td className="px-5 py-4"><StatusPill status={sale.status} /></td><td className="px-5 py-4 text-right font-semibold">{peso(sale.amount)}</td></tr>)}</tbody></table></div></div>
}

function Overview({ sales, setActive }) {
  return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-zinc-500">Sunday, September 7</p><h2 className="mt-1 font-display text-3xl font-semibold tracking-tight">Good morning, Admin.</h2></div><button className="primary-btn self-start"><Plus size={16} /> Add product</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={WalletCards} label="Gross revenue" value="₱486,820" change="12.4%" accent="bg-violet-100 text-violet-700 dark:bg-violet-400/15 dark:text-violet-300" /><StatCard icon={ShoppingBag} label="Total orders" value="148" change="8.7%" accent="bg-blue-100 text-blue-700 dark:bg-blue-400/15 dark:text-blue-300" /><StatCard icon={Users} label="New customers" value="39" change="15.2%" accent="bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300" /><StatCard icon={Box} label="Low stock items" value="7" change="2" up={false} accent="bg-amber-100 text-amber-700 dark:bg-amber-400/15 dark:text-amber-300" /></div><div className="grid gap-6 xl:grid-cols-[1.55fr_.75fr]"><SalesChart /><div className="surface-card p-6"><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-semibold">Sales by category</h2><p className="mt-1 text-xs text-zinc-500">This month</p></div><button><MoreHorizontal size={18} /></button></div><div className="mt-8 space-y-6">{[['Electric', '46%', 'bg-violet-500'], ['Acoustic', '29%', 'bg-amber-400'], ['Bass', '15%', 'bg-cyan-500'], ['Classical', '10%', 'bg-rose-400']].map(([label, value, color]) => <div key={label}><div className="mb-2 flex justify-between text-xs"><span>{label}</span><span className="font-semibold">{value}</span></div><div className="h-2 rounded-full bg-zinc-100 dark:bg-white/5"><motion.div initial={{ width: 0 }} animate={{ width: value }} transition={{ duration: .8 }} className={`h-full rounded-full ${color}`} /></div></div>)}</div></div></div><RecentSales sales={sales} onViewAll={() => setActive('sales')} /></motion.div>
}

function SalesDirectory({ sales }) {
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('All')
  const filtered = useMemo(() => sales.filter((sale) => (status === 'All' || sale.status === status) && `${sale.id} ${sale.customer} ${sale.product} ${sale.email}`.toLowerCase().includes(query.toLowerCase())), [sales, query, status])
  return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-zinc-500">All storefront transactions</p><h2 className="mt-1 font-display text-3xl font-semibold tracking-tight">Sales directory</h2></div><button className="secondary-btn self-start"><Download size={15} /> Export CSV</button></div><div className="surface-card mt-7 overflow-hidden"><div className="flex flex-col gap-3 border-b border-zinc-200 p-5 dark:border-white/10 sm:flex-row"><label className="input-shell flex-1"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent py-3 text-sm outline-none" placeholder="Search order, customer, email, or product" /></label><label className="input-shell"><SlidersHorizontal size={15} /><select value={status} onChange={(e) => setStatus(e.target.value)} className="appearance-none bg-transparent py-3 pr-6 text-sm outline-none"><option>All</option><option>Paid</option><option>Processing</option><option>Pending</option><option>Refunded</option></select><ChevronDown size={13} /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="bg-zinc-50 text-[9px] uppercase tracking-[.15em] text-zinc-400 dark:bg-white/[.025]"><th className="px-5 py-4">Order ID</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Product</th><th className="px-5 py-4">Date</th><th className="px-5 py-4">Payment</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Total</th><th className="w-12" /></tr></thead><tbody className="divide-y divide-zinc-100 dark:divide-white/5">{filtered.map((sale) => <tr key={sale.id} className="text-xs hover:bg-zinc-50 dark:hover:bg-white/[.025]"><td className="px-5 py-4 font-semibold">{sale.id}</td><td className="px-5 py-4"><p className="font-medium">{sale.customer}</p><p className="mt-1 text-[10px] text-zinc-500">{sale.email}</p></td><td className="max-w-[210px] truncate px-5 py-4 text-zinc-500">{sale.product}</td><td className="px-5 py-4 text-zinc-500">{sale.date}</td><td className="px-5 py-4 text-zinc-500">{sale.payment}</td><td className="px-5 py-4"><StatusPill status={sale.status} /></td><td className="px-5 py-4 text-right font-semibold">{peso(sale.amount)}</td><td className="pr-4"><button className="icon-btn h-8 w-8"><MoreHorizontal size={15} /></button></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-zinc-200 px-5 py-4 text-xs text-zinc-500 dark:border-white/10"><span>Showing {filtered.length} of {sales.length} sales</span><div className="flex gap-2"><button className="rounded-lg border border-zinc-200 px-3 py-2 dark:border-white/10">Previous</button><button className="rounded-lg border border-zinc-200 px-3 py-2 dark:border-white/10">Next</button></div></div></div></motion.div>
}

function ProductsView() {
  return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><div className="flex items-end justify-between"><div><p className="text-sm text-zinc-500">Catalog management</p><h2 className="mt-1 font-display text-3xl font-semibold">Products</h2></div><button className="primary-btn"><Plus size={16} /> Add product</button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{fallbackProducts.map((product) => <div key={product.id} className="surface-card flex gap-4 p-4"><img src={product.image} alt="" className="h-24 w-20 rounded-xl object-cover" /><div className="min-w-0 flex-1"><p className="text-[10px] uppercase tracking-widest text-zinc-500">{product.brand} · {product.category}</p><p className="mt-2 truncate text-sm font-semibold">{product.name}</p><div className="mt-4 flex items-end justify-between"><div><p className="text-sm font-semibold">{peso(product.price)}</p><p className={`mt-1 text-[10px] ${product.stock <= 3 ? 'text-amber-500' : 'text-zinc-500'}`}>{product.stock} in stock</p></div><button className="icon-btn"><MoreHorizontal size={16} /></button></div></div></div>)}</div></motion.div>
}

function CustomersView({ sales }) {
  const customers = sales.map((sale) => ({ name: sale.customer, email: sale.email, order: sale.id, spent: sale.amount }))
  return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><p className="text-sm text-zinc-500">Customer records</p><h2 className="mt-1 font-display text-3xl font-semibold">Customers</h2><div className="surface-card mt-7 overflow-hidden"><div className="grid gap-px bg-zinc-200 dark:bg-white/10 sm:grid-cols-2 xl:grid-cols-3">{customers.map((customer) => <div key={customer.email} className="bg-white p-5 dark:bg-panel"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-zinc-100 text-sm font-bold dark:bg-white/5">{customer.name.split(' ').map((part) => part[0]).join('')}</div><div><p className="text-sm font-semibold">{customer.name}</p><p className="text-[10px] text-zinc-500">{customer.email}</p></div></div><div className="mt-5 flex justify-between border-t border-zinc-100 pt-4 text-xs dark:border-white/5"><span className="text-zinc-500">Latest {customer.order}</span><span className="font-semibold">{peso(customer.spent)}</span></div></div>)}</div></div></motion.div>
}

export default function AdminDashboard({ theme, setTheme, onStore, onLogout }) {
  const [active, setActive] = useState('overview')
  const [menuOpen, setMenuOpen] = useState(false)
  const [sales, setSales] = useState(fallbackSales)
  useEffect(() => { fetch('/api/admin/sales').then((response) => response.json()).then((data) => data.sales?.length && setSales(data.sales)).catch(() => {}) }, [])
  return <div className="min-h-screen bg-stone-50 dark:bg-ink"><Sidebar active={active} setActive={setActive} open={menuOpen} setOpen={setMenuOpen} onStore={onStore} onLogout={onLogout} /><div className="lg:pl-[270px]"><DashboardHeader active={active} theme={theme} setTheme={setTheme} setOpen={setMenuOpen} /><main className="p-5 sm:p-8 xl:p-10">{active === 'overview' && <Overview sales={sales} setActive={setActive} />}{active === 'sales' && <SalesDirectory sales={sales} />}{active === 'products' && <ProductsView />}{active === 'customers' && <CustomersView sales={sales} />}</main></div></div>
}
